"""Initial schema

Revision ID: a0779863e19c
Revises: 
Create Date: 2026-02-01 22:01:00.791850

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a0779863e19c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
